export const THEMES: Record<string, Record<string, string>> = {
  "vscode-dark-plus": {
    "--bg-primary": "#1e1e1e",
    "--bg-secondary": "#252526",
    "--bg-tertiary": "#333333",
    "--bg-input": "#3c3c3c",
    "--border-color": "#454545",
    "--text-primary": "#cccccc",
    "--text-secondary": "#969696",
    "--accent-color": "#007acc",
    "--accent-hover": "#0062a3",
    "--selection-color": "#094771",
    "--list-hover-bg": "#2a2d2e",
    "--list-active-bg": "#37373d",
    "--list-active-fg": "#ffffff",
    "--tab-active-bg": "#1e1e1e",
    "--tab-inactive-bg": "#2d2d2d",
    "--tab-border": "#007acc",
  },
  "vscode-light-plus": {
    "--bg-primary": "#ffffff",
    "--bg-secondary": "#f3f3f3",
    "--bg-tertiary": "#e8e8e8",
    "--bg-input": "#ffffff",
    "--border-color": "#e5e5e5",
    "--text-primary": "#333333",
    "--text-secondary": "#616161",
    "--accent-color": "#007acc",
    "--accent-hover": "#0062a3",
    "--selection-color": "#e4f6ff",
    "--list-hover-bg": "#e8e8e8",
    "--list-active-bg": "#0060c0",
    "--list-active-fg": "#ffffff",
    "--tab-active-bg": "#ffffff",
    "--tab-inactive-bg": "#ececec",
    "--tab-border": "#007acc",
  },
  "github-dark": {
    "--bg-primary": "#0d1117",
    "--bg-secondary": "#161b22",
    "--bg-tertiary": "#21262d",
    "--bg-input": "#0d1117",
    "--border-color": "#30363d",
    "--text-primary": "#c9d1d9",
    "--text-secondary": "#8b949e",
    "--accent-color": "#58a6ff",
    "--accent-hover": "#1f6feb",
    "--selection-color": "#1f6feb",
    "--list-hover-bg": "#161b22",
    "--list-active-bg": "#1f6feb",
    "--list-active-fg": "#ffffff",
    "--tab-active-bg": "#0d1117",
    "--tab-inactive-bg": "#161b22",
    "--tab-border": "#58a6ff",
  },
  "github-light": {
    "--bg-primary": "#ffffff",
    "--bg-secondary": "#f6f8fa",
    "--bg-tertiary": "#eaeef2",
    "--bg-input": "#ffffff",
    "--border-color": "#d0d7de",
    "--text-primary": "#24292f",
    "--text-secondary": "#57606a",
    "--accent-color": "#0969da",
    "--accent-hover": "#0550ae",
    "--selection-color": "#0969da",
    "--list-hover-bg": "#eaeef2",
    "--list-active-bg": "#0969da",
    "--list-active-fg": "#ffffff",
    "--tab-active-bg": "#ffffff",
    "--tab-inactive-bg": "#f6f8fa",
    "--tab-border": "#0969da",
  },
  monokai: {
    "--bg-primary": "#272822",
    "--bg-secondary": "#1e1f1c",
    "--bg-tertiary": "#3e3d32",
    "--bg-input": "#414339",
    "--border-color": "#1e1f1c",
    "--text-primary": "#f8f8f2",
    "--text-secondary": "#75715e",
    "--accent-color": "#a6e22e",
    "--accent-hover": "#66d9ef",
    "--selection-color": "#49483e",
    "--list-hover-bg": "#3e3d32",
    "--list-active-bg": "#a6e22e",
    "--list-active-fg": "#272822",
    "--tab-active-bg": "#272822",
    "--tab-inactive-bg": "#1e1f1c",
    "--tab-border": "#a6e22e",
  },
  dracula: {
    "--bg-primary": "#282a36",
    "--bg-secondary": "#21222c",
    "--bg-tertiary": "#44475a",
    "--bg-input": "#282a36",
    "--border-color": "#44475a",
    "--text-primary": "#f8f8f2",
    "--text-secondary": "#6272a4",
    "--accent-color": "#bd93f9",
    "--accent-hover": "#ff79c6",
    "--selection-color": "#44475a",
    "--list-hover-bg": "#44475a",
    "--list-active-bg": "#bd93f9",
    "--list-active-fg": "#282a36",
    "--tab-active-bg": "#282a36",
    "--tab-inactive-bg": "#21222c",
    "--tab-border": "#bd93f9",
  },
  "solarized-dark": {
    "--bg-primary": "#002b36",
    "--bg-secondary": "#073642",
    "--bg-tertiary": "#586e75",
    "--bg-input": "#002b36",
    "--border-color": "#073642",
    "--text-primary": "#839496",
    "--text-secondary": "#586e75",
    "--accent-color": "#2aa198",
    "--accent-hover": "#268bd2",
    "--selection-color": "#073642",
    "--list-hover-bg": "#073642",
    "--list-active-bg": "#2aa198",
    "--list-active-fg": "#002b36",
    "--tab-active-bg": "#002b36",
    "--tab-inactive-bg": "#073642",
    "--tab-border": "#2aa198",
  },
  // Fallback/Legacy
  "vs-dark": {
    "--bg-primary": "#1e1e1e",
    "--bg-secondary": "#252526",
    "--bg-tertiary": "#333333",
    "--bg-input": "#3c3c3c",
    "--border-color": "#454545",
    "--text-primary": "#cccccc",
    "--text-secondary": "#969696",
    "--accent-color": "#007acc",
    "--accent-hover": "#0062a3",
    "--selection-color": "#094771",
    "--list-hover-bg": "#2a2d2e",
    "--list-active-bg": "#37373d",
    "--list-active-fg": "#ffffff",
    "--tab-active-bg": "#1e1e1e",
    "--tab-inactive-bg": "#2d2d2d",
    "--tab-border": "#007acc",
  },
};

export const THEME_RULES: Record<string, any[]> = {
  "github-dark": [
    { token: "keyword", foreground: "ff7b72" },
    { token: "string", foreground: "a5d6ff" },
    { token: "comment", foreground: "8b949e" },
    { token: "function", foreground: "d2a8ff" },
    { token: "type", foreground: "79c0ff" },
    { token: "variable", foreground: "c9d1d9" },
    { token: "number", foreground: "79c0ff" },
    { token: "class", foreground: "f0883e" },
  ],
  "github-light": [
    { token: "keyword", foreground: "d73a49" },
    { token: "string", foreground: "032f62" },
    { token: "comment", foreground: "6a737d" },
    { token: "function", foreground: "6f42c1" },
    { token: "type", foreground: "24292e" },
    { token: "variable", foreground: "24292e" },
    { token: "number", foreground: "005cc5" },
    { token: "class", foreground: "e36209" },
  ],
  monokai: [
    { token: "keyword", foreground: "f92672" },
    { token: "string", foreground: "e6db74" },
    { token: "comment", foreground: "75715e" },
    { token: "function", foreground: "a6e22e" },
    { token: "number", foreground: "ae81ff" },
    { token: "type", foreground: "66d9ef" },
    { token: "class", foreground: "a6e22e" },
    { token: "variable", foreground: "f8f8f2" },
  ],
  dracula: [
    { token: "keyword", foreground: "ff79c6" },
    { token: "string", foreground: "f1fa8c" },
    { token: "comment", foreground: "6272a4" },
    { token: "function", foreground: "50fa7b" },
    { token: "type", foreground: "8be9fd" },
    { token: "number", foreground: "bd93f9" },
    { token: "class", foreground: "8be9fd" },
    { token: "variable", foreground: "f8f8f2" },
  ],
  "solarized-dark": [
    { token: "keyword", foreground: "859900" },
    { token: "string", foreground: "2aa198" },
    { token: "comment", foreground: "586e75" },
    { token: "function", foreground: "268bd2" },
    { token: "type", foreground: "b58900" },
    { token: "number", foreground: "d33682" },
    { token: "class", foreground: "cb4b16" },
    { token: "variable", foreground: "839496" },
  ],
  "vscode-light-plus": [
    // Basic VS Code Light tokens if needed to override 'vs'
  ],
};
